Jc fix/register
xxvunborn/car-frontend pull request #10
Opened 2017-06-08 00:20 UTC by jcarrionramos

2017-06-08 00:46 UTC, xxvunborn requested changes

2017-06-08 00:46 UTC, xxvunborn commented on src/components/Header/component/register.js
> -    this.state = initialState;
why delete the binds, they are important

2017-06-08 00:46 UTC, xxvunborn commented on src/components/Header/component/register.js
> +     this.state.user.password === "") {
why !(function) return true, and not (function) return false?

2017-06-08 01:00 UTC, xxvunborn commented on src/components/Header/component/register.js
> -        onTouchTap={this.handleClose}
handleClose require

2017-06-08 01:36 UTC, jcarrionramos commented on src/components/Header/component/register.js
> -    this.state = initialState;
suck it 🖕

2017-06-08 01:36 UTC, jcarrionramos commented on src/components/Header/component/register.js
> +     this.state.user.password === "") {
tomorrow ✌️

2017-06-08 01:36 UTC, jcarrionramos commented on src/components/Header/component/register.js
> -        onTouchTap={this.handleClose}
sorry 😭

2017-06-09 05:04 UTC, xxvunborn approved these changes

2017-06-09 12:41 UTC, jcarrionramos commented
Merge?

2017-06-10 21:21 UTC, merged